version: '3.8'

services:
  mongo:
    image: mongo:8.0.12-rc0-noble
    container_name: blugger-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    # A variável MONGO_URI aqui não é usada e pode ser removida

  whaha:
    image: devlikeapro/waha:latest
    platform: linux/amd64
    container_name: whaha
    ports:
      - '3000:3000'
    environment:
      - API_TOKEN=${WHAHA_TOKEN}
      - WHATSAPP_STARTUP_MODE=normal
      - DISABLE_LOGOUT=false
    volumes:
      - ./whatsapp-data:/app/data

  api:
    build: .
    container_name: blugger-bot-api
    ports:
      - '3031:3031'
    depends_on:
      - whaha
      - mongo
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/bluggerbot  # 👈 Adicionado aqui

volumes:
  mongo_data:
